spring:
  application:
    # 应用名称
    name: 'config-client-dev'
com:
  pingfangushi:
    learning:
      user:
        username: 'test'
        password: '$2a$10$.oTtme6dDwynGav3m4sqIeVm3QsqC6uiGzxmc.gZDWJIBd4Jiq9Si'